version: "3.3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

volumes:
  postgres_data: